trigger:
- develop

pool:
  vmImage: 'windows-latest'

variables:
  solution: 'source/Lib.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- checkout: self
  fetchDepth: 0

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    arguments: '-c Release -p:Publish=true'
